const fs = require('fs');
const envConfig = fs.readFileSync('./.env.local', 'utf8').split('\n').forEach(line => {
  const match = line.match(/^([^=]+)=(.*)$/);
  if (match) process.env[match[1].trim()] = match[2].trim();
});
const nodemailer = require('nodemailer');

async function sendTestEmail() {
  const user = process.env.GMAIL_USER;
  const pass = process.env.GMAIL_APP_PASSWORD;

  if (!user || !pass) {
    console.error("Error: Missing GMAIL_USER or GMAIL_APP_PASSWORD in .env.local");
    process.exit(1);
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: user,
      pass: pass,
    },
  });

  const sampleEmail = 'user@example.com';
  const samplePassword = 'AutoGenerated123!';
  const maxLimit = '$5,000'; // Example limit

  const htmlContent = `
    <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
      <h2 style="color: #0056b3;">Thank you for registering with debbit OS!</h2>
      <p>Your account has been successfully created.</p>
      <div style="background-color: #f8f9fa; padding: 15px; border-radius: 8px; margin: 20px 0;">
        <p><strong>Your Email ID:</strong> ${sampleEmail}</p>
        <p><strong>Your Temporary Password:</strong> ${samplePassword}</p>
        <p><strong>Your Maximum Limit:</strong> ${maxLimit}</p>
      </div>
      <p>Please log in and change your password immediately.</p>
      <br/>
      <p>Best regards,<br/>The debbit OS Team</p>
    </div>
  `;

  console.log('Attempting to send test email to ' + user + '...');

  try {
    const info = await transporter.sendMail({
      from: `"debbit OS" <${user}>`,
      to: user, // Sending to themselves to test
      subject: 'Welcome to debbit OS! (Test Email)',
      html: htmlContent,
    });
    console.log('Success! Test email sent.');
    console.log('Message ID:', info.messageId);
  } catch (error) {
    console.error('Failed to send email:', error);
  }
}

sendTestEmail();
