// =============================================================================
// debbit OS · 195 Sovereign Countries & Currency Data
//
// Kept in sync with apps/desktop/lib/countries.js (same data, ES export
// instead of CommonJS) so a business created here matches what the desktop
// onboarding wizard offers — country_code/currency_code/tax_regime enums
// for all of these already exist on the Supabase side (migration 049).
// =============================================================================

export const SPECIALIZED_CONFIG = {
  MY: {
    name: 'Malaysia', flag: '🇲🇾', currency: 'MYR',
    reg_label:  'SSM No. (e.g. 202201012345)',
    tax_label:  'SST Registration No.',
    regimes: [
      { value: 'MY_SST_6',  label: 'SST 6% — Standard Services' },
      { value: 'MY_SST_10', label: 'SST 10% — Luxury / Selected Goods' },
    ],
    default_regime: 'MY_SST_6',
    fiscal_year_start: 1,
    note: 'MyInvois (LHDN) e-invoicing supported',
  },
  AE: {
    name: 'UAE', flag: '🇦🇪', currency: 'AED',
    reg_label:  'Trade License No.',
    tax_label:  'TRN (Tax Registration Number)',
    regimes: [
      { value: 'UAE_VAT_5', label: 'UAE VAT 5%' },
    ],
    default_regime: 'UAE_VAT_5',
    fiscal_year_start: 1,
    note: 'Standard 5% VAT',
  },
  SA: {
    name: 'Saudi Arabia', flag: '🇸🇦', currency: 'SAR',
    reg_label:  'CR No. (Commercial Registration)',
    tax_label:  'VAT Registration No.',
    regimes: [
      { value: 'KSA_VAT_15', label: 'KSA VAT 15%' },
    ],
    default_regime: 'KSA_VAT_15',
    fiscal_year_start: 1,
    note: 'ZATCA e-invoice + Zakat corporate tax supported',
  },
  ID: {
    name: 'Indonesia', flag: '🇮🇩', currency: 'IDR',
    reg_label:  'NIB (Nomor Induk Berusaha)',
    tax_label:  'NPWP',
    regimes: [
      { value: 'ID_PPN_11', label: 'PPN 11%' },
    ],
    default_regime: 'ID_PPN_11',
    fiscal_year_start: 1,
    note: 'Indonesian tax regime supported',
  },
  IN: {
    name: 'India', flag: '🇮🇳', currency: 'INR',
    reg_label:  'CIN / LLPIN / Registration No.',
    tax_label:  'GSTIN',
    regimes: [
      { value: 'IN_GST_0',  label: 'GST 0%' },
      { value: 'IN_GST_5',  label: 'GST 5%' },
      { value: 'IN_GST_12', label: 'GST 12%' },
      { value: 'IN_GST_18', label: 'GST 18% (Standard)' },
      { value: 'IN_GST_28', label: 'GST 28% (Luxury)' },
    ],
    default_regime: 'IN_GST_18',
    fiscal_year_start: 4,
    note: 'CGST + SGST split, GST-3B / GSTR-1 compliance supported',
  },
}

export const ALL_195_COUNTRIES = [
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', currency: 'AFN' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱', currency: 'ALL' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', currency: 'DZD' },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩', currency: 'EUR' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', currency: 'AOA' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', currency: 'XCD' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', currency: 'ARS' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲', currency: 'AMD' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', currency: 'AUD' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', currency: 'EUR' },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', currency: 'AZN' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', currency: 'BSD' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', currency: 'BHD' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', currency: 'BDT' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧', currency: 'BBD' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾', currency: 'BYN' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', currency: 'EUR' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', currency: 'BZD' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', currency: 'XOF' },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹', currency: 'BTN' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', currency: 'BOB' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', currency: 'BAM' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', currency: 'BWP' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', currency: 'BRL' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', currency: 'BND' },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', currency: 'BGN' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', currency: 'XOF' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', currency: 'BIF' },
  { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻', currency: 'CVE' },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', currency: 'KHR' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', currency: 'XAF' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', currency: 'CAD' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', currency: 'XAF' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', currency: 'XAF' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', currency: 'CLP' },
  { code: 'CN', name: 'China', flag: '🇨🇳', currency: 'CNY' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', currency: 'COP' },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲', currency: 'KMF' },
  { code: 'CD', name: 'Congo (DRC)', flag: '🇨🇩', currency: 'CDF' },
  { code: 'CG', name: 'Congo (Republic)', flag: '🇨🇬', currency: 'XAF' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', currency: 'CRC' },
  { code: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮', currency: 'XOF' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', currency: 'EUR' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', currency: 'CUP' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', currency: 'EUR' },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', currency: 'CZK' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', currency: 'DKK' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', currency: 'DJF' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲', currency: 'XCD' },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', currency: 'DOP' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', currency: 'USD' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', currency: 'EGP' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻', currency: 'USD' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', currency: 'XAF' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷', currency: 'ERN' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', currency: 'EUR' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', currency: 'SZL' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', currency: 'ETB' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', currency: 'FJD' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', currency: 'EUR' },
  { code: 'FR', name: 'France', flag: '🇫🇷', currency: 'EUR' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', currency: 'XAF' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲', currency: 'GMD' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪', currency: 'GEL' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', currency: 'EUR' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', currency: 'GHS' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', currency: 'EUR' },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩', currency: 'XCD' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', currency: 'GTQ' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳', currency: 'GNF' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', currency: 'XOF' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', currency: 'GYD' },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹', currency: 'HTG' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', currency: 'HNL' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', currency: 'HUF' },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸', currency: 'ISK' },
  { code: 'IN', name: 'India', flag: '🇮🇳', currency: 'INR' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', currency: 'IDR' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', currency: 'IRR' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', currency: 'IQD' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', currency: 'EUR' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱', currency: 'ILS' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', currency: 'EUR' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲', currency: 'JMD' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', currency: 'JPY' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴', currency: 'JOD' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', currency: 'KZT' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', currency: 'KES' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮', currency: 'AUD' },
  { code: 'KP', name: 'North Korea', flag: '🇰🇵', currency: 'KPW' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', currency: 'KRW' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', currency: 'KWD' },
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', currency: 'KGS' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', currency: 'LAK' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻', currency: 'EUR' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧', currency: 'LBP' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', currency: 'LSL' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', currency: 'LRD' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', currency: 'LYD' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', currency: 'CHF' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹', currency: 'EUR' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', currency: 'EUR' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', currency: 'MGA' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', currency: 'MWK' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', currency: 'MYR' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', currency: 'MVR' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', currency: 'XOF' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹', currency: 'EUR' },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', currency: 'USD' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷', currency: 'MRU' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺', currency: 'MUR' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', currency: 'MXN' },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲', currency: 'USD' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩', currency: 'MDL' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', currency: 'EUR' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳', currency: 'MNT' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪', currency: 'EUR' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', currency: 'MAD' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', currency: 'MZN' },
  { code: 'MM', name: 'Myanmar (Burma)', flag: '🇲🇲', currency: 'MMK' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦', currency: 'NAD' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷', currency: 'AUD' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵', currency: 'NPR' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', currency: 'EUR' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', currency: 'NZD' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', currency: 'NIO' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', currency: 'XOF' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', currency: 'NGN' },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', currency: 'MKD' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', currency: 'NOK' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', currency: 'OMR' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', currency: 'PKR' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼', currency: 'USD' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', currency: 'ILS' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', currency: 'PAB' },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', currency: 'PGK' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', currency: 'PYG' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', currency: 'PEN' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', currency: 'PHP' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', currency: 'PLN' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', currency: 'EUR' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', currency: 'QAR' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', currency: 'RON' },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', currency: 'RUB' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', currency: 'RWF' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', currency: 'XCD' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨', currency: 'XCD' },
  { code: 'VC', name: 'Saint Vincent & Grenadines', flag: '🇻🇨', currency: 'XCD' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', currency: 'WST' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲', currency: 'EUR' },
  { code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹', currency: 'STN' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', currency: 'SAR' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', currency: 'XOF' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', currency: 'RSD' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', currency: 'SCR' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', currency: 'SLE' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', currency: 'SGD' },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', currency: 'EUR' },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮', currency: 'EUR' },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', currency: 'SBD' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴', currency: 'SOS' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', currency: 'ZAR' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸', currency: 'SSP' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', currency: 'EUR' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', currency: 'LKR' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩', currency: 'SDG' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', currency: 'SRD' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', currency: 'SEK' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', currency: 'CHF' },
  { code: 'SY', name: 'Syria', flag: '🇸🇾', currency: 'SYP' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼', currency: 'TWD' },
  { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯', currency: 'TJS' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', currency: 'TZS' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', currency: 'THB' },
  { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱', currency: 'USD' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', currency: 'XOF' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', currency: 'TOP' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', currency: 'TTD' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', currency: 'TND' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', currency: 'TRY' },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲', currency: 'TMT' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', currency: 'AUD' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', currency: 'UGX' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', currency: 'UAH' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', currency: 'AED' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', currency: 'GBP' },
  { code: 'US', name: 'United States', flag: '🇺🇸', currency: 'USD' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', currency: 'UYU' },
  { code: 'UZ', name: 'Uzbekistan', flag: 'UZS', currency: 'UZS' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', currency: 'VUV' },
  { code: 'VA', name: 'Vatican City', flag: '🇻🇦', currency: 'EUR' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', currency: 'VES' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', currency: 'VND' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪', currency: 'YER' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲', currency: 'ZMW' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', currency: 'ZWG' },
]

// Build full COUNTRY_CONFIG map including specialized and standard configs
export const FULL_COUNTRY_CONFIG = { ...SPECIALIZED_CONFIG }

ALL_195_COUNTRIES.forEach((c) => {
  if (!FULL_COUNTRY_CONFIG[c.code]) {
    FULL_COUNTRY_CONFIG[c.code] = {
      name: c.name,
      flag: c.flag,
      currency: c.currency,
      reg_label: 'Business Registration No.',
      tax_label: 'Tax Identification Number (TIN / VAT / GST)',
      regimes: [
        { value: `${c.code}_STANDARD`, label: `Standard Tax / VAT (${c.name})` },
      ],
      default_regime: `${c.code}_STANDARD`,
      fiscal_year_start: 1,
      note: `Standard configuration for ${c.name}`,
    }
  }
})

export function getCountryConfig(code) {
  if (!code) return null
  return FULL_COUNTRY_CONFIG[code.toUpperCase()] || null
}
